# Generated by Django 5.1.5 on 2025-01-31 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='resort',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
