# Generated by Django 5.1.5 on 2025-02-10 22:24

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0002_resort_location_alter_resort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='skiarea',
            fields=[
                ('skiarea_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('scalerank', models.CharField(max_length=255)),
                ('passaffiliation', models.CharField(max_length=255)),
                ('partnered', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('operatingstatus', models.CharField(max_length=255)),
                ('alpine', models.BooleanField()),
                ('nordic', models.BooleanField()),
                ('website', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
