# Generated by Django 5.1.5 on 2025-02-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0003_skiarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiarea',
            name='alpine',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='nordic',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='operatingstatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='partnered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='passaffiliation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='scalerank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='skiarea',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
