# Generated by Django 5.1.5 on 2025-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0004_alter_skiarea_alpine_alter_skiarea_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiarea',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
