# Generated by Django 5.1.5 on 2025-02-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0005_alter_skiarea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiarea',
            name='website',
            field=models.CharField(null=True),
        ),
    ]
