# Generated by Django 5.1.5 on 2025-02-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0006_alter_skiarea_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skiarea',
            name='passaffiliation',
            field=models.CharField(default='Unaffiliated', max_length=255, null=True),
        ),
    ]
