# Generated by Django 5.1.5 on 2025-02-18 16:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resorts', '0007_alter_skiarea_passaffiliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skiarea',
            old_name='location',
            new_name='geom',
        ),
        migrations.CreateModel(
            name='aerialway',
            fields=[
                ('aerialway_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aerialway_type', models.CharField()),
                ('occupancy', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('detachable', models.BooleanField()),
                ('bubble', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('ski_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski_resorts.skiarea')),
            ],
        ),
        migrations.CreateModel(
            name='glade',
            fields=[
                ('glade_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('difficulty', models.CharField()),
                ('piste_type', models.CharField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('ski_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski_resorts.skiarea')),
            ],
        ),
        migrations.CreateModel(
            name='trail',
            fields=[
                ('trail_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('difficulty', models.CharField()),
                ('piste_type', models.CharField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('ski_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski_resorts.skiarea')),
            ],
        ),
    ]
